### PR TITLE
fix(Youtube): wrong uploader after short

### LINKED ISSUE #6842: [Youtube]Shorts
### Steps to Reproduce

1. Go to Youtube Homepage
2. Play Shorts
3. Go back to Youtube Homepage
4. Play Something in Recommendations
5. Check Premid on discord and it shows the wrong uploader

### Expected Behavior

updated the uploader

### Actual Behavior

it still uses shorts video uploader name

### Page URL

https://www.youtube.com/

### Screenshots

image
image

### Operating System

Windows 7 64bit

### Browser and Version

Brave Browser v1.44.105

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Resolves #6842 Fixed bug that uploader was used after watching a short.
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/Y/YouTube/presence.ts [hunk 1]
```diff
@@ -227,6 +233,7 @@ presence.on("UpdateData", async () => {
 			);
 		}
 
+		if (!YoutubeShorts) uploaderShorts = void 0;
```
Comment (Bas950) [inline websites/Y/YouTube/presence.ts:236]: Why not set it to null or undefined?

Comment (DarkVillager) [reply websites/Y/YouTube/presence.ts:236]: eslint

Comment (Bas950) [reply websites/Y/YouTube/presence.ts:236]: Don't think that that is the best way to fix it

**Review by Bas950 — APPROVED** [review]

**Comment by DarkVillager** [comment]
@EncryptedDev should review but Bas didn’t assign him?

**Comment by EncryptedDev** [comment]
> @EncryptedDev should review but Bas didn’t assign him?

thanks mr maintainer

**Review by EncryptedDev — APPROVED** [review]
