### PR TITLE
fix(Disney+): fix presence

### LINKED ISSUE #7027: Disney+ presence only showing browsing
### Steps to Reproduce

1. go to disneyplus.com (or for my case disneyplus.com/ph)
2. go to a movie or a show
3. check presence

### Expected Behavior

Show what movie / series i was watching

### Actual Behavior

Only showed browsing even if i was watching a movie

### Page URL

https://www.apps.disneyplus.com/ph/shows/modern-family/8549/en-garde/1770001034/watch

### Screenshots

image

### Operating System

Windows 10

### Browser and Version

Firefox 106.0.5

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Resolves #7027
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by ipexadev** [comment]
Fix the Problems please.

**Comment by DarkVillager** [comment]
> Fix the Problems please.

Patience.

**Review by Bas950 — DISMISSED** [review]

File: websites/D/Disney+/presence.ts [hunk 1]
```diff
@@ -12,216 +13,219 @@ async function getStrings() {
...
+								presence.timestampFromFormat(stamps[1])
+							)[1];
+						}
+					}
+					break;
+				}
+				case !!document.querySelector('[data-gv2containerkey="contentMeta"]'): {
+					if (pathname.includes("series")) {
+						presenceData.details = privacy
+							? "Viewing a serie"
```
Comment (theusaf) [inline websites/D/Disney+/presence.ts:86]:
```suggestion
							? "Viewing a series"
```

**Review by theusaf — CHANGES_REQUESTED** [review]

**Review by theusaf — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]
