### PR TITLE
fix(Replit): patch presence & refactor

### LINKED ISSUE #5747: Replit | replit.com
### Description

presence is only showing viewing homepage, even though i have opened a file in replit.

### Steps to Reproduce

go to replit.com, make a template, wait for it to show in discord

### Screenshots

image
showing like this even if i have opened a file in replit

### Expected Behavior

to show, viewing file, line of code (number), language, time elapsed

### Actual Behavior

only showing viewing homepage

### Page URL

https://replit.com/~

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.35.100

### PR DESCRIPTION
**Pull request by kyrie25**
**Describe the changes in this pull request:**
Resolves #5747 & refactor presence (eg. uses object destructing vars, replace deprecated `.substr()` with `.slice()`, etc. ) & added `browsingTimestamp` as requested in the issue
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

Please keep in mind that in most of the screenshots, `startTimestamp` was *yet* to be added so it is not present, not because it broke
image
image
image
image

</details>

### CODE REVIEW

File: websites/R/Replit/presence.ts [hunk 1]
```diff
@@ -1,75 +1,93 @@
...
 		presenceData.details = "Creating new repl:";
 		presenceData.state = `${
-			document.querySelector<HTMLInputElement>("#languageSelector-input").value
+			document.querySelector<HTMLInputElement>(
+				"input[data-cy='new-repl-language-input']"
+			).value.length === 0
+				? "No languages chosen"
+				: document.querySelector<HTMLInputElement>(
+						"input[data-cy='new-repl-language-input']"
+				  ).value
```
Comment (Slowlife01) [inline websites/R/Replit/presence.ts:57]:
```suggestion
			document.querySelector<HTMLInputElement>(
				"input[data-cy='new-repl-language-input']"
			).value || "No languages chosen"
```

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]
