### PR TITLE
Fixed Bandcamp

### LINKED ISSUE #4128: [Presence | Bug] Bandcamp
**Describe the Bug**
The music feed, in addition to the collections page, wishlist and following is not working.

**Steps to Reproduce**

1. Have the presence of Bandcamp
Attention: For you to access the feed (`bandcamp.com/[username]/feed`), and also the collections page, you need to create an account for the service.
2. Access the site in these parts, as an album (ex: `waterfrontdining.bandcamp.com/album/the-valley`) or track (ex: `waterfrontdining.bandcamp.com/track/sore-feet`) page is still working.

**Expected Behavior**
The site has probably updated, and presence is not working as it should.

**Screenshots**

Collection/wishlist/following:
image

------------------------
Feed: 
image

**Environment**
- OS: Windows 10
- Browser: Opera GX
- Version:  LVL 3 (core: 77.0.4054.257) (64 bits)

**Additional context**
Change the logo (largeImage) of the presence, with the new changes in the part of the Discord profile, the logo was camouflaged:
image

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #4128
- Now works on profile
- Now works on people's Favourite genres, Collections & Wishlist
- Small code improvement
image
image
image

### CODE REVIEW

**Review by Bas950 — DISMISSED** [review]

File: websites/B/Bandcamp/presence.ts [hunk 1]
```diff
@@ -222,26 +237,25 @@ presence.on("UpdateData", async () => {
...
+      }`;
       presenceData.startTimestamp = browsingStamp;
     } else {
       presenceData.startTimestamp = browsingStamp;
       presenceData.details = "Viewing:";
       presenceData.state = document.querySelector("head > title").textContent;
     }
   }
-  if (presenceData.details == null) {
+  if (presenceData.details === null) {
```
Comment (Slowlife01) [inline websites/B/Bandcamp/presence.ts:257]:
```suggestion
  if (!presenceData.details) {
```

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]
