### PR TITLE
Fix iQIYI | new presence for Line TV | new presence for Viu

### LINKED ISSUE #2124: Line TV | tv.line.me/linetv.tw
- [x] Is it a popular site?  (This depends of the person)
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Line TV

The presence should display the name of the presence "Line TV", the name of what are you currently playing, the chapter, and if possible, the minute.

image

### LINKED ISSUE #2898: VIU | viu.com
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 

- [x] Is the site locked to a specific country/region?
This site is available in Hong Kong, India, Singapore, Malaysia, Thailand, Philippines, United Arab Emirates, Bahrain, Egypt, Indonesia, Jordan, Kuwait, Oman, Qatar, Saudi Arabia, Myanmar and South Africa

- [x] Is the site a paid service? (e.g. Netflix, Hulu)
premium account and free account

- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.viu.com | VIU

**What should the Presence display?** 
This site is about video streaming service I think it should be show like Youtube or Netflix (series or movie name and have time progess)

**If possible, please provide a logo for the service (512x512 minimum)** 

viu

Thank you

### PR DESCRIPTION
**Pull request by SlowLife1661**
## New Presence Line TV

image
image
image
image

Resolves #2124 

## New Presence Viu

image
image
image

Resolves #2898 

Might as well add more pages to these Presences

### CODE REVIEW

**Comment by SlowLife1661** [comment]
DeepCode don't want break but others 2 wants aaaa

**Comment by SlowLife1661** [comment]
#2124 <

**Comment by SlowLife1661** [comment]
For #2124

File: websites/I/iQIYI/presence.ts [hunk 1]
```diff
@@ -56,144 +54,86 @@ presence.on("UpdateData", async () => {
...
-              ? (await strings).watchVideo
-              : isMovie
-              ? (await strings).watchMovie
-              : (await strings).watchEpisode,
-            url: `https://www.iq.com/play/${
-              document.URL.split("?")[0].split("/")[4]
-            }`
+
+      URLItem: string = JSON['parse'](document.querySelectorAll('script[type="application/ld+json"]')[1]?.innerHTML || "{}")[0]?.itemListElement[0]?.item ?? document.URL,
+      video: HTMLVideoElement = document.querySelector('video'),
```
Comment (Bas950) [inline websites/I/iQIYI/presence.ts:65]: why not JSON.parse() ?

Comment (SlowLife1661) [reply websites/I/iQIYI/presence.ts:65]: I will check If I can use it since the last time it returns error that I can't use JSON.parse()

File: websites/V/Viu/dist/metadata.json [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+      "movie"
+    ],
+    "category": "videos",
+    "settings": [
+      {
+        "id": "lang",
+        "multiLanguage": true
+      },
+      {
+        "id": "buttons?",
```
Comment (Bas950) [inline websites/V/Viu/dist/metadata.json:29]: please remove the ? out of the id

File: websites/L/Line TV/dist/metadata.json [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+        "drama",
+        "video"
+    ],
+    "category": "videos",
+    "settings": [{
+      "id": "lang",
+      "multiLanguage": true
+    },
+    {
+      "id": "Buttons?",
```
Comment (Bas950) [inline websites/L/Line TV/dist/metadata.json:26]: same here

**Review by Bas950 — CHANGES_REQUESTED** [review]

**Review by Bas950 — APPROVED** [review]

File: websites/L/Line TV/presence.ts [hunk 4]
```diff
@@ -0,0 +1,227 @@
...
+let oldLang: string = null,
+    strings: Promise<LangStrings> = getStrings();
+
+presence.on("UpdateData", async () => {
+    const presenceData: PresenceData = {
+        largeImageKey: "linetv_logo",
+        startTimestamp: browsingStamp,
+        details: (await strings).browse,
+        smallImageKey: "reading",
+        smallImageText: (await strings).browse
```
Comment (ririxidev) [inline websites/L/Line TV/presence.ts:46]: Actually doubling this text isn't good. delete smallImageText .-.

File: websites/V/Viu/presence.ts [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+let browsingStamp = Math.floor(Date.now() / 1000),
+    strings: Promise<LangStrings> = getStrings(),
+    oldLang: string = null;
+
+presence.on("UpdateData", async () => {
+    const presenceData: PresenceData = {
+      details: (await strings).browse,
+      smallImageKey: "reading",
+      smallImageText: (await strings).browse,
```
Comment (ririxidev) [inline websites/V/Viu/presence.ts:27]: same here as above (delete)

File: websites/V/Viu/presence.ts [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+      episode: "general.episode",
+      searchFor: "general.searchFor",
+      watchVideo: "general.buttonWatchVideo",
+      viewPage: "general.viewPage",
+      watchMovie: "general.buttonViewMovie",
+      watchEpisode: "general.buttonViewEpisode",
+      searching: "general.search"
+  }, await presence.getSetting("lang"));
+
+let browsingStamp = Math.floor(Date.now() / 1000),
```
Comment (ririxidev) [inline websites/V/Viu/presence.ts:19]: image
EKHEM

**Review by ririxidev — DISMISSED** [review]

File: websites/V/Viu/presence.ts (hunk 6 above)
Comment (SlowLife1661) [reply websites/V/Viu/presence.ts:19]: kek

File: websites/L/Line TV/dist/metadata.json [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+    "url": "tv.line.me",
+    "description": {
+      "en": "LINE TV is a global video streaming service. You can watch high-quality video content in a variety of categories such as TV dramas, entertainment shows."
+    },
+    "service": "Line TV",
+    "version": "1.0.0",
+    "logo": "https://i.imgur.com/F2sWIqN.png",
+    "thumbnail": "https://i.imgur.com/5sqClBZ.png",
+    "color": "#ffffff",
+    "tags": [
```
Comment (Bas950) [inline websites/L/Line TV/dist/metadata.json:16]: shouldnt you use the green color from their logo?

**Review by Bas950 — CHANGES_REQUESTED** [review]

File: websites/L/Line TV/dist/metadata.json (hunk 7 above)
Comment (SlowLife1661) [reply websites/L/Line TV/dist/metadata.json:16]: Sure

**Review by Bas950 — APPROVED** [review]

**Review by StrikerFRFX — APPROVED** [review]
