### PR TITLE
fix(KissAsian): fix presence

### LINKED ISSUE #7676: KissAsian | kissasian.fm - not showing which movie we are watching
### Steps to Reproduce

1. Was trying to watch kdrama but it didn't show what kdrama i'm watching it only says kissasian
2. This is the link https://kissasian.fm/drama/strong-woman-do-bong-soon-episode-1
3. Pls fix it

### Expected Behavior

It should show the title of the movie and how much time it left

### Actual Behavior

But now when i watch, it only says "KissAsian" thats all

### Page URL

https://kissasian.fm/drama/strong-woman-do-bong-soon-episode-1

### Screenshots

image-74

### Operating System

Windows 11

### Browser and Version

Chrome

### Additional Comments

Pls fix it asap tysm

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

- Resolves #7676
- Add regex to match everything but disqus.org or .com (because those websites stop the iframe injection from working.)
- Fix elements
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/K/KissAsian/iframe.ts [hunk 1]
```diff
@@ -1,36 +1,11 @@
...
-		document.querySelector(
-			"#vstr > div.jw-wrapper.jw-reset > div.jw-media.jw-reset > video"
-		) ||
-		document.querySelector("video");
+	const video: HTMLVideoElement = document.querySelector(
+		"video,[class='jw-video jw-reset']"
+	);
 
-	if (video && !isNaN(video.duration)) {
+	if (video && !isNaN(video?.duration)) {
```
Comment (Bas950) [inline websites/K/KissAsian/iframe.ts:8]: The question mark seems useless because of the first case in the if...

Comment (DarkVillager) [reply websites/K/KissAsian/iframe.ts:8]: Some videos don't have duration somehow, until a bit later.

Comment (Bas950) [reply websites/K/KissAsian/iframe.ts:8]: Yea thats why it starts with if (video)

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]
