### PR TITLE
perf(Reddit): fix switching client, which lags browser

### LINKED ISSUE #7891: Reddit | www.reddit.com - Presence causes memory leak
### Steps to Reproduce

1.  Add reddit presence
2. Go to reddit either old or new reddit

### Expected Behavior

Normal ram usage

### Actual Behavior

Ram fills quickly, fills page file, causes browser to lock up and if left for long enough your pc to bluescreen

### Page URL

https://www.reddit.com/

### Screenshots

https://github.com/PreMiD/Presences/assets/155543447/bc281ef5-1905-4716-8d24-c30b9bb3b504

### Operating System

Windows 10

### Browser and Version

Firefox 121 x64

### Additional Comments

I turned on privacy mode and typically when you first go to reddit when you have the presence it takes a few seconds before the ram spikes. with privacy mode it was instant.

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

- Resolves #7891
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/R/Reddit/presence.ts [hunk 1]
```diff
@@ -1,20 +1,21 @@
...
 	nickname: string,
 	rpanTitle: string,
 	strings: Awaited<ReturnType<typeof getStrings>>,
-	oldLang: string = null;
+	oldLang: string = null,
+	containsNetflix: boolean;
+
+const enum Assets {
+	Logo = "https://cdn.rcd.gg/PreMiD/websites/R/Reddit/assets/logo.png",
+	NetflixLogo = "https://styles.redditmedia.com/t5_2qoxj/styles/communityIcon_j9f3pbthqfy01.png",
```
Comment (theusaf) [inline websites/R/Reddit/presence.ts:17]: Asset is very small and not square

**Review by theusaf — CHANGES_REQUESTED** [review]

File: websites/R/Reddit/presence.ts [hunk 2]
```diff
@@ -35,28 +36,56 @@ async function getStrings() {
 	);
 }
 
-const startTimestamp = Math.floor(Date.now() / 1000),
+const presences: { [key in PresenceClients]?: Presence } = {
+		[PresenceClients.Reddit]: presence,
+	},
+	startTimestamp = Math.floor(Date.now() / 1000),
 	oldReddit = document.querySelector("._1tvdSTbdxaK-BnUbzUIqIY") === null;
```
Comment (theusaf) [inline websites/R/Reddit/presence.ts:43]: Maybe there's a better method for this?
```suggestion
	oldReddit = document.querySelector("header") === null;
```

File: websites/R/Reddit/presence.ts (hunk 1 above)
Comment (DarkVillager) [reply websites/R/Reddit/presence.ts:17]: Oopsie

File: websites/R/Reddit/presence.ts (hunk 2 above)
Comment (DarkVillager) [inline websites/R/Reddit/presence.ts:43]:
```suggestion
	oldReddit = document.querySelector("#default-header") === null;
```

File: websites/R/Reddit/presence.ts [hunk 3]
```diff
@@ -1,20 +1,21 @@
...
 	nickname: string,
 	rpanTitle: string,
 	strings: Awaited<ReturnType<typeof getStrings>>,
-	oldLang: string = null;
+	oldLang: string = null,
+	containsNetflix: boolean;
+
+const enum Assets {
+	Logo = "https://cdn.rcd.gg/PreMiD/websites/R/Reddit/assets/logo.png",
+	NetflixLogo = "https://cdn.discordapp.com/icons/741794683482538074/a_f893fbdc993664e0c2957dead21e1007.gif?size=512",
```
Comment (Bas950) [inline websites/R/Reddit/presence.ts:17]:
```suggestion
	NetflixLogo = `https://i.imgur.com${"/Aw5rIOI.gif"}`,
```

**Review by Bas950 — CHANGES_REQUESTED** [review]

File: websites/R/Reddit/presence.ts [hunk 4]
```diff
@@ -40,7 +40,7 @@ const presences: { [key in PresenceClients]?: Presence } = {
 		[PresenceClients.Reddit]: presence,
 	},
 	startTimestamp = Math.floor(Date.now() / 1000),
-	oldReddit = document.querySelector("._1tvdSTbdxaK-BnUbzUIqIY") === null;
+	oldReddit = document.querySelector("#default-header") === null;
```
Comment (theusaf) [inline websites/R/Reddit/presence.ts:43]: I'm unable to find this element on my new or old reddit.

**Review by theusaf — CHANGES_REQUESTED** [review]

File: websites/R/Reddit/presence.ts (hunk 4 above)
Comment (DarkVillager) [reply websites/R/Reddit/presence.ts:43]: Interesting
image

Comment (DarkVillager) [inline websites/R/Reddit/presence.ts:43]:
```suggestion
	oldReddit = document.querySelector(".default-header") === null;
```

File: websites/R/Reddit/presence.ts [hunk 5]
```diff
@@ -1,20 +1,21 @@
...
 	nickname: string,
 	rpanTitle: string,
 	strings: Awaited<ReturnType<typeof getStrings>>,
-	oldLang: string = null;
+	oldLang: string = null,
+	containsNetflix: boolean;
+
+const enum Assets {
+	Logo = "https://cdn.rcd.gg/PreMiD/websites/R/Reddit/assets/logo.png",
+	NetflixLogo = "https://i.imgur.com/Aw5rIOI.gif",
```
Comment (Bas950) [inline websites/R/Reddit/presence.ts:17]:
```suggestion
	NetflixLogo = `https://i.imgur.com${"/Aw5rIOI.gif"}`,
```

**Review by Bas950 — CHANGES_REQUESTED** [review]

File: websites/R/Reddit/presence.ts (hunk 5 above)
Comment (DarkVillager) [reply websites/R/Reddit/presence.ts:17]: why???

Comment (theusaf) [reply websites/R/Reddit/presence.ts:17]: There seems to be a bug with resizing/uploading gifs apparently

File: websites/R/Reddit/presence.ts [hunk 6]
```diff
@@ -35,28 +36,56 @@ async function getStrings() {
 	);
 }
 
-const startTimestamp = Math.floor(Date.now() / 1000),
-	oldReddit = document.querySelector("._1tvdSTbdxaK-BnUbzUIqIY") === null;
+const presences: { [key in PresenceClients]?: Presence } = {
+		[PresenceClients.Reddit]: presence,
+	},
+	startTimestamp = Math.floor(Date.now() / 1000),
+	oldReddit = document.querySelector(".default-header") === null;
```
Comment (theusaf) [inline websites/R/Reddit/presence.ts:43]: Since this element appears on old reddit, the comparison is incorrect.
```suggestion
	oldReddit = document.querySelector(".default-header") !== null;
```
```suggestion
	oldReddit = !!document.querySelector(".default-header");
```

**Review by theusaf — CHANGES_REQUESTED** [review]

File: websites/R/Reddit/presence.ts (hunk 5 above)
Comment (theusaf) [reply websites/R/Reddit/presence.ts:17]: Although, there are examples where there are no problems:
* https://cdn.rcd.gg/PreMiD/websites/N/Netflix/assets/0.gif
* https://cdn.rcd.gg/PreMiD/websites/B/BeatLeader/assets/81.gif
* https://cdn.rcd.gg/PreMiD/websites/D/Discovery/assets/0.gif
* etc

@Bas950

Comment (Bas950) [reply websites/R/Reddit/presence.ts:17]: The Netflix and Discovery ones I had to manually override
I mean we can test if it works with this one...

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]
