### PR TITLE
fix(Replit): rewrite presence to fix issues

### LINKED ISSUE #8218: Replit | replit.com - doesn't work directly on replit.com
### Steps to Reproduce

The replit presence works if you open it from replit.it (which changes to com) but if you try to open it from replit.com (currently URL) then it doesn't work. Also, the logo is outdated so the logo should be changed. 

### Expected Behavior

If I working on something with replit.com, then it should be detected 

### Actual Behavior

You have to open replit.it first before so it starts working

### Page URL

https://replit.com/

### Screenshots

_No response_

### Operating System

Windows 11

### Browser and Version

Chrome Ver. 123.0.6312.60

### Additional Comments

As long as it works on replit.com then the issue should be fixed.

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Resolves #8218 
rewrite presence to fix issues
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/R/Replit/presence.ts [hunk 1]
```diff
@@ -1,90 +1,127 @@
...
+const enum Assets {
+	CodeLine = "https://i.imgur.com/HNnl3oL.png",
+}
+
+presence.on("UpdateData", async () => {
 	const presenceData: PresenceData = {
-			details: "Viewing unsupported page",
-			largeImageKey:
-				"https://cdn.rcd.gg/PreMiD/websites/R/Replit/assets/logo.png",
+			largeImageKey: "https://i.imgur.com/rKlupJp.png",
```
Comment (theusaf) [inline websites/R/Replit/presence.ts:14]: It may make sense to combine this with the other Assets.

File: websites/R/Replit/presence.ts [hunk 2]
```diff
@@ -1,90 +1,127 @@
...
+						.querySelector(".cm-lineNumbers")
+						?.querySelectorAll(".cm-gutterElement"),
+					activeLine = document
+						.querySelector(".cm-lineNumbers")
+						?.querySelector(".cm-activeLineGutter")?.textContent;
+				presenceData.details = hash.split("#")?.[1]
+					? `Viewing replit: ${title} | File: ${hash.split("#")?.[1]}`
+					: `Viewing replit: ${title}`;
+				presenceData.state = `Created by: ${pathname.split("/")[1]}`;
+				presenceData.buttons = [{ label: "View Replit", url: href }];
```
Comment (theusaf) [inline websites/R/Replit/presence.ts:57]: I think the more accurate term is "REPL". "Replit" is the website which contains "REPLs"

**Review by theusaf — CHANGES_REQUESTED** [review]

**Review by theusaf — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]
