### PR TITLE
fix(MyCanal): changed new path to img tag

### LINKED ISSUE #7458: myCANAL | www.canalplus.com - details not showing properly
### Steps to Reproduce

any channel actually, picked the first one that came in the live section. I started a movie on replay and it displayed everything properly (screenshot 1) but on live it just shows that im looking for a channel. Sadly cant screen that im ACTUALLY watching a chan cause canal puts a black screen .. 

### Expected Behavior

display the program and or channel

### Actual Behavior

showing "is navigating" 

### Page URL

https://www.canalplus.com/live/?channel=312

### Screenshots

2023-07-01 19_49_23-#general _ BTS SIO - Discord
not displaying the channel nor the show

image
even tho im watching one 

image
not live 

image
and it works

### Operating System

win11

### Browser and Version

brave v 114 1 52 129

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by itsmelouis**
## Description 
I fixed the issue when browsing a live channel, the presence wasn't functionning properly. 
Resolves #7458 

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>  

image  

image

</details>

### CODE REVIEW

File: websites/M/myCANAL/presence.ts [hunk 1]
```diff
@@ -53,14 +53,14 @@ presence.on("UpdateData", async () => {
...
-						`#\\3${channelID} > a > div > div > div > div > div > img`
+						`#\\3${channelID}_toFocus > div.cardLogoChannel___WSRDl.cardLogoChannel--shadow___bE5Zx > div > img`
 					).alt
 				}`;
 				[presenceData.startTimestamp, presenceData.endTimestamp] =
 					presence.getTimestamps(video.currentTime, video.duration);
 				presenceData.largeImageKey = showCover
 					? document.querySelector<HTMLImageElement>(
-							`#\\3${channelID} > a > div > div > div > div > div > img`
+							`#\\3${channelID}_toFocus > div.cardLogoChannel___WSRDl.cardLogoChannel--shadow___bE5Zx > div > img`
```
Comment (theusaf) [inline websites/M/myCANAL/presence.ts:63]: Try using a more dynamic selector if possible, for example:
```css
div[class*="cardLogoChannel"]
```

**Review by theusaf — CHANGES_REQUESTED** [review]

**Comment by itsmelouis** [comment]
Done. Sorry for the wait 😕

**Review by Bas950 — APPROVED** [review]
