### PR TITLE
fix(Notion): complete rework of the Activity

### LINKED ISSUE #7220: Notion | www.notion.so
### Steps to Reproduce

1 - Add the Notion presence, if you don't have it.
2 - Opens any page in your workspace.
3 - Observe

### Expected Behavior

I would wait for the details of the presence to appear.

### Actual Behavior

While loading the page, the details appeared, but when it ends, it simply disappears (see the video).

### Page URL

https://www.notion.so/[domain]/[page link]

### Screenshots

https://user-images.githubusercontent.com/68751594/223161910-bc7bb732-4a84-4b04-9da0-423298f051a6.mp4

image

### Operating System

Windows 10

### Browser and Version

Edge version 110.0.1587.63 (64 bits)

### Additional Comments

None

### PR DESCRIPTION
**Pull request by skullysmods**
## Description

Complete rework of the Activity
fix #7220 
> Ref: #10307

## Acknowledgements
- [x] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `npm run lint`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image
image
image
image

</details>

### CODE REVIEW

File: websites/N/Notion/presence.ts [hunk 1]
```diff
@@ -1,119 +1,378 @@
...
+    const x = (maxSize - img.width) / 2
+    const y = (maxSize - img.height) / 2
+    ctx.drawImage(img, x, y, img.width, img.height)
+
+    png = canvas.toDataURL('image/png')
   }
+
+  URL.revokeObjectURL(url)
+  return png
 }
```
Comment (Bas950) [inline websites/N/Notion/presence.ts:57]: Please cache this

**Review by Bas950 — CHANGES_REQUESTED** [review]

**Review by Bas950 — APPROVED** [review]
