### PR TITLE
fix(Youtube): channel name & image being null

### LINKED ISSUE #8406: YouTube | youtube.com - going to some channels results in "Viewing Channel: null"
### Steps to Reproduce

1. Go to https://www.youtube.com/@WirtualTV (it happens with other channels, this one i tested for)
2. You should be able to see the Presence showing "Viewing Channel: null"

### Expected Behavior

The presence should show the channel name, in this format: "Viewing Channel: WirtualTV"

### Actual Behavior

The presence shows the string "Viewing Channel: null"

### Page URL

https://www.youtube.com/@WirtualTV

### Screenshots

image

### Operating System

Fedora Linux 40 (Workstation Edition)

### Browser and Version

Version 127.0.6485.0 (Official Build) dev (64-bit)

### Additional Comments

This bug only happens in certain channels, for example going to https://www.youtube.com/@BillieEilish works as expected

this could be related to the "#text.ytd-channel-name" selector being only available in some channels, and not others

you can also see that this selector is going through the videos list, picking the first video to get the channel name, which could be unreliable as channel author can link to videos from other channels, however its somewhat unlikely.

i'd suggest using the link to get the channel handle and use that instead, however it could be undesirable as it's different to the current behaviour

### PR DESCRIPTION
**Pull request by darkvillager2**
## Description 

Resolves #8406 
fix(Youtube">: channel name being null
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/Y/YouTube/presence.ts [hunk 1]
```diff
@@ -331,7 +331,8 @@ presence.on("UpdateData", async () => {
 					!document.querySelector("#text.ytd-channel-name")?.textContent &&
 					documentTitle.includes(
 						document.querySelector("#text.ytd-channel-name")?.textContent
-					)
+					) &&
+					document.querySelector("#text.ytd-channel-name")?.textContent
```
Comment (Bas950) [inline websites/Y/YouTube/presence.ts:335]: It gets ! checked and then !! checked?

**Review by Bas950 — CHANGES_REQUESTED** [review]

File: websites/Y/YouTube/presence.ts (hunk 1 above)
Comment (darkvillager2) [reply websites/Y/YouTube/presence.ts:335]: Confused but this somehow fixes it?

Comment (Bas950) [reply websites/Y/YouTube/presence.ts:335]: well one of these checks seems useless...

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]
