### PR TITLE
Replace App Ids that were broken

### LINKED ISSUE #3890: [Presence | Bug] Kodi
**Describe the Bug**

So, the problem is that Kodi presence isnt working, it just dont show on discord status. I tried everything that i was told in the description, but still doesnt show. 
**Steps to Reproduce**

1.  https://github.com/PreMiD/Presences/blob/master/websites/K/Kodi/readme.md

**Expected Behavior**

I expected that the Kodi would show on my discord status
**Screenshots**

image
image

**Environment**

- OS:  Windows 10
- Browser:  Brave
- Version:  1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit)
  

**Additional context**

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #3890
Replaced almost all app ids from [Alexx](https://premid.app/users/604182077088202784) cause they were utterly broken due to account deletion. (Still broken & Unmaintained: [Tubi](https://premid.app/store/presences/Tubi) & [Edgenuity](https://premid.app/store/presences/Edgenuity))
image

image
Folding@home's app id has been replaced & has been fixed.

Yahoo Mail's logo should work, it just hasn't been cached by discord yet.

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
You didnt bump versions on all of them...

File: websites/0-9/9anime/iframe.ts [hunk 1]
```diff
@@ -11,4 +11,4 @@ iframe.on("UpdateData", async () => {
       });
     }
   }
-});
+});
```
Comment (ririxidev) [inline websites/0-9/9anime/iframe.ts:14]: revert

File: websites/F/Folding@home/dist/metadata.json [hunk 2]
```diff
@@ -1,20 +1,30 @@
 {
+  "$schema": "https://schemas.premid.app/metadata/1.3",
+  "service": "Folding@Home",
```
Comment (ririxidev) [inline websites/F/Folding@home/dist/metadata.json:3]:
```suggestion
  "service": "Folding@home",
```

File: websites/F/Folding@home/presence.ts [hunk 3]
```diff
@@ -1,29 +1,33 @@
...
-    cpuUsage = document.querySelector(
-      "div.ui-progressbar-value.ui-widget-header.ui-corner-left"
-    );
-    contributingProject = document.querySelector("a.sbSelector");
-
-    presenceData.details = "Contributing to: " + contributingProject.innerText;
-    presenceData.state = "Project Progress: " + cpuUsage.innerText;
-  } else {
-    presenceData.details = "Can't read page";
-  }
```
Comment (ririxidev) [inline websites/F/Folding@home/presence.ts:21]: wait wait wait why did you removed it and changing to to less info??

File: websites/M/myCANAL/presence.ts [hunk 4]
```diff
@@ -16,34 +16,32 @@ function getTimestamps(
   videoTime: number,
   videoDuration: number
 ): Array<number> {
-  var startTime = Date.now();
-  var endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
+  const startTime = Date.now(), 
+  endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
   return [Math.floor(startTime / 1000), endTime];
 }
```
Comment (ririxidev) [inline websites/M/myCANAL/presence.ts:22]: presence.getTimestamps and remove comments :)

File: websites/M/myCANAL/presence.ts [hunk 5]
```diff
@@ -16,34 +16,32 @@ function getTimestamps(
...
 
-var elapsed = Math.floor(Date.now() / 1000);
-var title;
+const elapsed = Math.floor(Date.now() / 1000);
```
Comment (ririxidev) [inline websites/M/myCANAL/presence.ts:24]: merge with other const

File: websites/M/myCANAL/presence.ts [hunk 6]
```diff
@@ -16,34 +16,32 @@ function getTimestamps(
...
+      const path = document.location.pathname;
       if (path.includes("/live/")) {
         title = document.querySelector("._3tdt8zwgvMCJ6v_sElXneQ").textContent;
         data.smallImageKey = "live";
         data.smallImageText = (await strings).live;
         data.startTimestamp = elapsed;
       } else {
         title = document.querySelector(".bodyTitle___DZEtt").textContent;
-        var timestamps = getTimestamps(
+        const timestamps = getTimestamps(
```
Comment (ririxidev) [inline websites/M/myCANAL/presence.ts:44]:
```suggestion
        const timestamps = presence.getTimestamps(
```

File: websites/Q/Q-dance/presence.ts [hunk 7]
```diff
@@ -1,27 +1,24 @@
...
-    clientId: "619768959717343242"
+const presence = new Presence({
+    clientId: "844107169205190686"
   }),
   strings = presence.getStrings({
     live: "presence.activity.live"
   });
-
-var elapsed = Math.floor(Date.now() / 1000);
+   let elapsed = Math.floor(Date.now() / 1000);
```
Comment (ririxidev) [inline websites/Q/Q-dance/presence.ts:7]: let -> const and merge

File: websites/S/Showtime/presence.ts [hunk 8]
```diff
@@ -16,20 +16,20 @@ function getTimestamps(
   videoTime: number,
   videoDuration: number
 ): Array<number> {
-  var startTime = Date.now();
-  var endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
+  const startTime = Date.now(),
+  endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
   return [Math.floor(startTime / 1000), endTime];
 }
```
Comment (ririxidev) [inline websites/S/Showtime/presence.ts:22]: presence.getTimestamps()

File: websites/S/Showtime/presence.ts [hunk 9]
```diff
@@ -46,12 +46,12 @@ presence.on("UpdateData", async () => {
       description = "Movie";
     }
 
-    var timestamps = getTimestamps(
+    const timestamps = getTimestamps(
```
Comment (ririxidev) [inline websites/S/Showtime/presence.ts:49]:
```suggestion
    const timestamps = presence.getTimestamps(
```

File: websites/S/Stadia/dist/metadata.json [hunk 10]
```diff
@@ -1,15 +1,21 @@
...
     "nl": "Stadia is een door Google geëxploiteerde cloudgamingdienst. Er wordt geadverteerd dat het videogames kan streamen tot 4K-resolutie bij 60 frames per seconde met ondersteuning voor high-dynamic-range, naar spelers via de talrijke datacenters van het bedrijf over de hele wereld, op voorwaarde dat ze een internetverbinding met voldoende hoge snelheid gebruiken. Het is toegankelijk via de Google Chrome-webbrowser op desktopcomputers, Pixel-smartphones, ondersteunde smartphones van Samsung, OnePlus, Razer en Asus, evenals Chrome OS-tablets en Chromecast voor tv-ondersteuning."
   },
   "service": "Stadia",
-  "version": "1.0.3",
+  "version": "1.0.4",
   "logo": "https://i.imgur.com/DwoRFyw.png",
   "thumbnail": "https://i.imgur.com/CyujQo7.png",
   "color": "#0081FF",
```
Comment (ririxidev) [inline websites/S/Stadia/dist/metadata.json:21]: Well about stadia - someone else is going to do it - so basically revert changes for now.

File: websites/S/Stadia/presence.ts [hunk 11]
```diff
@@ -1,5 +1,5 @@
 const presence = new Presence({
-  clientId: "713114770584109150"
+  clientId: "844107770402701332"
 });
 const browsingStamp = Math.floor(Date.now() / 1000);
 let gameName: HTMLElement;
```
Comment (ririxidev) [inline websites/S/Stadia/presence.ts:5]: Well about stadia - someone else is going to do it - so basically revert changes for now.

File: websites/T/TuneIn/presence.ts [hunk 12]
```diff
@@ -19,36 +19,34 @@ function getTimestamps(
...
+   parsedAudioTime = getTime(splitAudioTime),
+   parsedAudioDuration = getTime(splitAudioDuration),
 
-  var startTime = Date.now();
-  var endTime =
+  startTime = Date.now(),
+   endTime =
     Math.floor(startTime / 1000) - parsedAudioTime + parsedAudioDuration;
   return [Math.floor(startTime / 1000), endTime];
 }
```
Comment (ririxidev) [inline websites/T/TuneIn/presence.ts:32]: presence.getTimestamps()

File: websites/T/TuneIn/presence.ts [hunk 13]
```diff
@@ -19,36 +19,34 @@ function getTimestamps(
...
 
-var elapsed = Math.floor(Date.now() / 1000);
-var title, author;
+let elapsed = Math.floor(Date.now() / 1000), title, author;
```
Comment (ririxidev) [inline websites/T/TuneIn/presence.ts:34]: i think elapsed can be const

File: websites/T/TuneIn/presence.ts [hunk 14]
```diff
@@ -81,11 +79,10 @@ presence.on("UpdateData", async () => {
...
       title = document.querySelector("#playerTitle").textContent;
       author = document.querySelector("#playerSubtitle").textContent;
-      var audioTime = document.querySelector("#scrubberElapsed").textContent;
-      var audioDuration =
-        document.querySelector("#scrubberDuration").textContent;
-      var timestamps = getTimestamps(audioTime, audioDuration);
-      const paused = document.querySelector(
+      const audioTime = document.querySelector("#scrubberElapsed").textContent,
+      audioDuration = document.querySelector("#scrubberDuration").textContent,
+      timestamps = getTimestamps(audioTime, audioDuration),
```
Comment (ririxidev) [inline websites/T/TuneIn/presence.ts:84]:
```suggestion
      timestamps = presence.getTimestamps(audioTime, audioDuration),
```

**Review by rxri — CHANGES_REQUESTED** [review]

File: websites/F/Folding@home/presence.ts (hunk 3 above)
Comment (DarkVillager) [reply websites/F/Folding@home/presence.ts:21]: It contains almost all the same info just wait less lines of code (and without the can't read page).

Comment (ririxidev) [reply websites/F/Folding@home/presence.ts:21]: then do like `Project progress` etc

File: websites/F/Folding@home/iframe.ts [hunk 15]
```diff
@@ -0,0 +1,14 @@
...
+
+iframe.on("UpdateData", async () => {
+  const l1 = document.querySelector("#box-points-team > a"),
+  l2 = document.querySelector("#slot-0 > div.pu > div.pu-bar.ui-progressbar.ui-widget.ui-widget-content.ui-corner-all > div")
+  if (l1 && l2 !== undefined) {
+  iframe.send({
+    iframe_d: {
+ points: l1.textContent,
+ progress: l2.textContent,
+    }
```
Comment (Bas950) [inline websites/F/Folding@home/iframe.ts]: Use normal names, not 11, 12

**Review by Bas950 — CHANGES_REQUESTED** [review]

File: websites/T/TuneIn/presence.ts (hunk 13 above)
Comment (DarkVillager) [reply websites/T/TuneIn/presence.ts:34]: image

File: websites/0-9/9anime/iframe.ts (hunk 1 above)
Comment (ririxidev) [reply websites/0-9/9anime/iframe.ts:14]: revert - it's not reverted

File: websites/E/Edgenuity/presence.ts [hunk 16]
```diff
@@ -41,4 +41,4 @@ presence.on("UpdateData", async () => {
   } else {
     presence.setActivity(presenceData);
   }
-});
+});
```
Comment (ririxidev) [inline websites/E/Edgenuity/presence.ts:44]: revert?

File: websites/Q/Q-dance/presence.ts (hunk 7 above)
Comment (ririxidev) [reply websites/Q/Q-dance/presence.ts:7]: still not resolved

File: websites/S/Showtime/presence.ts (hunk 9 above)
Comment (ririxidev) [reply websites/S/Showtime/presence.ts:49]: b

File: websites/S/Stadia/presence.ts [hunk 17]
```diff
@@ -41,4 +41,4 @@ presence.on("UpdateData", async () => {
   } else {
     presence.setActivity(presenceData);
   }
-});
+});
```
Comment (ririxidev) [inline websites/S/Stadia/presence.ts:44]: revert

**Review by rxri — CHANGES_REQUESTED** [review]

File: websites/0-9/9anime/iframe.ts (hunk 1 above)
Comment (ririxidev) [reply websites/0-9/9anime/iframe.ts:14]: 🤷

File: websites/S/Stadia/presence.ts (hunk 17 above)
Comment (DarkVillager) [reply websites/S/Stadia/presence.ts:44]: how? I tried.

Comment (ririxidev) [reply websites/S/Stadia/presence.ts:44]: Revert changes in VSC for example 🤷 then do commit

Comment (DarkVillager) [reply websites/S/Stadia/presence.ts:44]: I did that but it still shows that

File: websites/Q/Q-dance/presence.ts (hunk 7 above)
Comment (DarkVillager) [reply websites/Q/Q-dance/presence.ts:7]: image

Comment (ririxidev) [reply websites/Q/Q-dance/presence.ts:7]: i don't see any sense in this code since elapsed can't be null tho 🤔

File: websites/S/Stadia/9anime/dist/metadata.json [hunk 18]
```diff
@@ -0,0 +1,27 @@
...
+  "color": "#694ba1",
+  "tags": [
+    "embedded-links",
+    "9anime",
+    "streaming"
+  ],
+  "category": "anime",
+  "regExp": "([a-z0-9-]+[.])*9anime([.][a-z]+)+[/]",
+  "iframe": true
+}
```
Comment (ririxidev) [inline websites/S/Stadia/9anime/dist/metadata.json:27]: what did you did? XD remove this folder. Why 9anime is in Stadia folder

File: websites/S/Stadia/9anime/iframe.ts [hunk 19]
```diff
@@ -0,0 +1,14 @@
...
+    const video: HTMLVideoElement = document.querySelector("video");
+    if (video != null && !isNaN(video.duration)) {
+      iframe.send({
+        duration: video.duration,
+        currentTime: video.currentTime,
+        paused: video.paused
+      });
+    }
+  }
+});
```
Comment (ririxidev) [inline websites/S/Stadia/9anime/iframe.ts:14]: like above

File: websites/S/Stadia/9anime/presence.ts [hunk 20]
```diff
@@ -0,0 +1,89 @@
...
+    }
+
+    presence.setActivity(data, !video.paused);
+  } else {
+    data.details = (await strings).browsing;
+    data.smallImageKey = "search";
+    data.smallImageText = (await strings).browsing;
+    presence.setActivity(data);
+  }
+});
```
Comment (ririxidev) [inline websites/S/Stadia/9anime/presence.ts:89]: like above

File: websites/S/Stadia/9anime/tsconfig.json [hunk 21]
```diff
@@ -0,0 +1,6 @@
+{
+  "extends": "../../../tsconfig.json",
+  "compilerOptions": {
+    "outDir": "./dist/"
+  }
+}
```
Comment (ririxidev) [inline websites/S/Stadia/9anime/tsconfig.json:6]: like above

File: websites/T/TuneIn/presence.ts (hunk 13 above)
Comment (ririxidev) [reply websites/T/TuneIn/presence.ts:10]: it can't be null since it's assigned right away

**Review by rxri — CHANGES_REQUESTED** [review]
also line 83 in TuneIn remove it

File: websites/S/Stadia/9anime/dist/metadata.json (hunk 18 above)
Comment (DarkVillager) [reply websites/S/Stadia/9anime/dist/metadata.json:27]: LMAO OOPS

File: websites/Q/Q-dance/presence.ts (hunk 7 above)
Comment (ririxidev) [reply websites/Q/Q-dance/presence.ts:7]: .

**Review by rxri — CHANGES_REQUESTED** [review]

File: websites/K/Kodi/presence.ts [hunk 22]
```diff
@@ -340,4 +340,4 @@ presence.on("UpdateData", async () => {
   } else {
     presence.setActivity(presenceData);
   }
-});
+});
```
Comment (ririxidev) [inline websites/K/Kodi/presence.ts:343]: revert?

**Review by rxri — CHANGES_REQUESTED** [review]
7plus:
image
Deno:
image
fix

**Comment by DarkVillager** [comment]
I'll asap.

File: websites/F/Folding@home/presence.ts [hunk 23]
```diff
@@ -1,29 +1,33 @@
-var presence = new Presence({
-  clientId: "704385469856612523"
+const presence = new Presence({
+  clientId: "812025934617509949"
 });
+let points: string,
+  progress: string;
+presence.on("iFrameData", (data: IFrameData) => {
+  points = data.iframe_d.points,
+  progress = data.iframe_d.progress;
```
Comment (ririxidev) [inline websites/F/Folding@home/presence.ts:8]: camelCase for `iframe_d`

File: websites/F/Folding@home/iframe.ts [hunk 24]
```diff
@@ -0,0 +1,14 @@
+const iframe = new iFrame();
+
+iframe.on("UpdateData", async () => {
+  const points = document.querySelector("#box-points-team > a"),
+  progress = document.querySelector("#slot-0 > div.pu > div.pu-bar.ui-progressbar.ui-widget.ui-widget-content.ui-corner-all > div");
+  if (progress && points !== undefined) {
+  iframe.send({
+    iframe_d: {
```
Comment (ririxidev) [inline websites/F/Folding@home/iframe.ts:8]: camelCase for `iframe_d`

File: websites/M/myCANAL/presence.ts [hunk 25]
```diff
@@ -54,7 +37,7 @@ presence.on("UpdateData", async () => {
         (data.startTimestamp = timestamps[0]),
           (data.endTimestamp = timestamps[1]);
```
Comment (ririxidev) [inline websites/M/myCANAL/presence.ts:38]:
```suggestion
        data.endTimestamp = endTimestamp;
```

File: websites/M/myCANAL/presence.ts [hunk 26]
```diff
@@ -1,49 +1,32 @@
...
         data.smallImageKey = "live";
         data.smallImageText = (await strings).live;
         data.startTimestamp = elapsed;
       } else {
         title = document.querySelector(".bodyTitle___DZEtt").textContent;
-        var timestamps = getTimestamps(
+        const timestamps = presence.getTimestamps(
           Math.floor(video.currentTime),
           Math.floor(video.duration)
         );
```
Comment (ririxidev) [inline websites/M/myCANAL/presence.ts:32]:
```suggestion
        const [, endTimestamp] = presence.getTimestamps(
          Math.floor(video.currentTime),
          Math.floor(video.duration)
        );
```

File: websites/Q/Q-dance/presence.ts (hunk 7 above)
Comment (ririxidev) [reply websites/Q/Q-dance/presence.ts:7]: still not fixed.

File: websites/S/Showtime/presence.ts [hunk 27]
```diff
@@ -46,12 +32,12 @@ presence.on("UpdateData", async () => {
       description = "Movie";
     }
 
-    var timestamps = getTimestamps(
+    const timestamps = presence.getTimestamps(
       Math.floor(video.currentTime),
       Math.floor(video.duration)
     );
```
Comment (ririxidev) [inline websites/S/Showtime/presence.ts:38]:
```suggestion
    const [, endTimestamp] = presence.getTimestamps(
      Math.floor(video.currentTime),
      Math.floor(video.duration)
    );
```

File: websites/S/Showtime/presence.ts [hunk 28]
```diff
@@ -66,13 +52,12 @@ presence.on("UpdateData", async () => {
...
-    var data: PresenceData = {
+    const data: PresenceData = {
       details: title,
       state: currentState,
-      largeImageKey: "showtime-logo",
+      largeImageKey: "logo",
       smallImageKey: smallImageKey,
       smallImageText: smallImageText,
-      startTimestamp: timestamps[0],
       endTimestamp: timestamps[1]
```
Comment (ririxidev) [inline websites/S/Showtime/presence.ts:61]:
```suggestion
      endTimestamp: endTimestamp
```

**Review by rxri — CHANGES_REQUESTED** [review]
idk what you broke but now I don't see Kodi presence and fix lines where you have for example
```(data.endTimestamp ...),
(data.startTimestamp ...)
``` 
instead of `;` and you create unnecessary brackets

**Comment by DarkVillager** [comment]
I didnt close it again??

**Review by rxri — DISMISSED** [review]

**Comment by ririxidev** [comment]
or maybe not, because I just noticed that you still didn't fix issue that I requested in first or second review.

**Comment by ririxidev** [comment]
image
idk how but fix

File: websites/F/Folding@home/iframe.ts (hunk 24 above)
Comment (Bas950) [reply websites/F/Folding@home/iframe.ts:8]: just setting a better name in general would be good

**Review by Bas950 — CHANGES_REQUESTED** [review]
Kodi needs version bump

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]
