### PR TITLE
fix(animepahe): fix getStrings constantly call

### LINKED ISSUE #6584: animepahe presence causes massive lag
### Steps to Reproduce

1. Watch any episode, let it sit for at least 10 minutes.
2. It starts to lag, noticeable by going in/out of full screen, trying to change episodes and quality.

### Expected Behavior

Nothing to barely noticeable lag

### Actual Behavior

Presence.getStrings gets called multiple times

### Page URL

URL changes every once in a while; unable to provide

### Screenshots

Profiler
devHelper.js

### Operating System

Windows 10

### Browser and Version

Chrome 103.0.5060.134 (Official Build) (64-bit)

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by RisingSunLight42**
## Description 

Resolves #6584 by redoing the getStrings() function in the presence file, the check to avoid useless calls to it was missing.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

animepahe_proof_1

animepahe_proof_3

animepahe_proof_2

</details>

### CODE REVIEW

**Comment by RisingSunLight42** [comment]
I've just edited the presence to fix this problem, but I think the code is a bit messy and not really maintanable/maybe too much complicated. Maybe someone should do a recoding of it.

File: websites/A/animepahe/presence.ts [hunk 1]
```diff
@@ -2,39 +2,43 @@
...
-			},
-			lang
-		);
-
-let iframeResponse = {
-	paused: true,
-	duration: 0,
-	currentTime: 0,
-};
+	clientId: "629355416714739732", // Contact if you want me to edit the discord assets/keys/whatever
```
Comment (EncryptedDev) [inline websites/A/animepahe/presence.ts:5]:
```suggestion
	clientId: "629355416714739732",
```

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Review by DarkVillager — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]
