### PR TITLE
Fixed Anime Digital Network Presence

### LINKED ISSUE #3622: [Presence | Bug] Anime Digital Network
**Describe the Bug**
The status is displaying "Browsing...", but starting an episode doesn't change the status.

**Steps to Reproduce**
1. Open https://animedigitalnetwork.fr/
2. Start an episode

**Expected Behavior**
The status should be updated with anime title, episode...

**Screenshots**
unknown (2)

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 90.0.4430.93 (64-bit)

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #3622
image

### CODE REVIEW

File: websites/A/AnimeDigitalNetwork/presence.ts [hunk 1]
```diff
@@ -37,17 +36,16 @@ presence.on("UpdateData", async () => {
...
+    const title = document
         .querySelector(
-          "#root > div > div > div.sc-qXJnB.ijvXfJ > div > div > div.sc-pAArZ.idjhKu > div:nth-child(2) > div > div > div > div.sc-jwDLgl.jjQkhb > div > h1"
+          "#root > div > div > div.sc-pbWVv.hTvDIL > div > div:nth-child(1) > div.sc-jWJfXU.sc-kbKFCX.ibhpg > div:nth-child(1) > div > div > h1 > a"
         )
-        .textContent.toLowerCase(),
-      title = t.charAt(0).toUpperCase() + t.slice(1),
+        .textContent,
       data = {
         details: "Browsing...",
```
Comment (ririxidev) [inline websites/A/AnimeDigitalNetwork/presence.ts:50]: well I think it should be:
```suggestion
        details: "Looking at",
```

**Review by ririxidev — CHANGES_REQUESTED** [review]
if you are making changes already please delete on line `30`, `startTimestamp: timestamps[0]`.

File: websites/A/AnimeDigitalNetwork/presence.ts [hunk 2]
```diff
@@ -47,7 +46,7 @@ presence.on("UpdateData", async () => {
         )
         .textContent,
       data = {
-        details: "Browsing...",
+        details: "Looking at...",
```
Comment (ririxidev) [inline websites/A/AnimeDigitalNetwork/presence.ts:49]: well I literally requested changes without these 3 dots. Remove them.
and im not `riri` ty

**Review by ririxidev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]
