### PR TITLE
fix(Anontpp): title not showing

### LINKED ISSUE #5832: Anontpp | goplay.anontpp.com
### Description

When watching a movie now, it doesn't display the title anymore and instead just says "Watching Movie"

### Steps to Reproduce

1. Go to this link
2. Click on any movie/feature films
3. Title not displayed on premid

### Screenshots

[

](url)

### Expected Behavior

Movie title to be displayed

### Actual Behavior

Title is missing, only "Watching Movie" is displayed

### Page URL

https://goplay.anontpp.com/

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

-

### PR DESCRIPTION
**Pull request by Slowlife01**
**Describe the changes in this pull request:**
Fixes #5832

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

image

</details>

### CODE REVIEW

File: websites/A/Anontpp/presence.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 const presence = new Presence({
 		clientId: "708314580304003124"
 	}),
-	strings: Promise<{ [key: string]: string }> = presence.getStrings({
+	newStrings = presence.getStrings({
 		play: "presence.playback.playing",
```
Comment (Bas950) [inline websites/A/Anontpp/presence.ts:5]: switch to general. strings

**Review by Bas950 — CHANGES_REQUESTED** [review]

**Review by Bas950 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]
