### PR TITLE
fix(WitAnime): Change URL and fix fetch from page

### LINKED ISSUE #10161: witanime | witanime.world
### Steps to Reproduce

Hey can you fix https://witanime.wolrd its changed to https://witanime.day/

### Expected Behavior

change link 

### Actual Behavior

they changed the link

### Page URL

https://witanime.day/

### Country

algeria

### Browser and Version

Version 141.0.7390.108 (Official Build) (64-bit)

### Screenshots

_No response_

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DxriaaaN**
## Description

Updating the presence for WitAnime. 
Resolves #10161 
## Acknowledgements
- [x] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `npm run lint`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/W/WitAnime/presence.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ async function getEpisodeInfo(text: string) {
         bannerImg = ActivityAssets.Logo
       }
       else {
-        const fetchUrl = `https://witanime.world/anime/${encodeURIComponent(slugForFetch)}/`
+        const fetchUrl = `https://witanime.day/anime/${encodeURIComponent(slugForFetch)}/`
```
Comment (theusaf) [inline websites/W/WitAnime/presence.ts:88]: Since both domains are supported in this activity, perhaps make the domain in this URL more dynamic to the hostname from the page

**Review by theusaf — CHANGES_REQUESTED** [review]

File: websites/W/WitAnime/presence.ts (hunk 1 above)
Comment (DxriaaaN) [reply websites/W/WitAnime/presence.ts]: Sorry i was wrong, the domain .world doesnt exist anymore. Its only .day Thanks for the correction, i changed sucefully the metadata acording to the new site url. I guess isnt are neccesary make it more dynamic!

**Review by Bas950 — APPROVED** [review]
