### PR TITLE
refactor(pixiv): redo codebase and fix bugs

### LINKED ISSUE #7035: Pixiv not working correctly
### Steps to Reproduce

1. Go to https://www.pixiv.net/ (will show "Viewing home page" on status as intended so far)
2. Press any artwork or user in the site
3. Rich presence will stop working or just show "Viewing home page" as status

### Expected Behavior

Display the artwork/tag/user/ pretty much anything else it should display

### Actual Behavior

Just shows "Viewing home page" / "Viewing dashboard" / "User settings"

### Page URL

https://www.pixiv.net/

### Screenshots

image

### Operating System

Windows 10

### Browser and Version

 Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### Additional Comments

Seems anything artwork/user related aside from the homepage and your own dashboard/settings is broken

### PR DESCRIPTION
**Pull request by RisingSunLight42**
### Changelog

- fix bugs in querySelectors
- replace tons of if statements by a Record
- replace others if statements by a Switch
- add buttons for some pages
- switched the owner metadata to me with the agreement of @Bas950 
- Resolves #7035 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

pixiv_proof_6

pixiv_proof_5

pixiv_proof_4

pixiv_proof_3

pixiv_proof_2

pixiv_proof_1

</details>

### CODE REVIEW

**Review by Bas950 — APPROVED** [review]

File: websites/P/pixiv/presence.ts [hunk 1]
```diff
@@ -1,195 +1,194 @@
...
+			state: "Workspace",
+		},
+		settinginfophp: { details: "Notification Settings" },
+		lives: { details: "Sketch- Browsing livestreams" },
+		popular: { details: "Sketch- Viewing popular posts" },
+		followings: { details: "Sketch- Viewing following posts" },
+		tagshistory: { details: "Sketch- Viewing tags:", state: "Featured tags" },
+		"upload.php": { details: "Submitting New Novel" },
+		discovery: { details: "Viewing Recommanded Novels" },
+		"ranking.php": { details: "Viewing Novels Ranking" },
```
Comment (EncryptedDev) [inline websites/P/pixiv/presence.ts:46]:
```suggestion
		"": { details: "Viewing homepage" },
		fanbox: { details: "Viewing fanbox" },
		event: { details: "Browsing events..." },
		"history.php": { details: "Browsing history" },
		bookmark: { details: "Viewing bookmarks" },
		"mypixivall.php": { details: "Browsing my pixiv" },
		group: { details: "Browsing group" },
		idea: { details: "Browsing idea" },
		howto: { details: "Browsing how-to" },
		eventadd: { details: "Ready to create an event" },
		profileevent: { details: "Manage event..." },
		premium: { details: "Viewing Premier Registered info" },
		"messages.php": { details: "Browsing private message" },
		"ugoiraupload.php": { details: "Submiting new Ugoira(Animations)" },
		manage: { details: "Managing artworks" },
		"settinguser.php": { details: "User settings", state: "Basic settings" },
		settingsnspost: {
			details: "User settings",
			state: "Post on social media",
		},
		"settingprofile.php": {
			details: "Profile settings",
			state: "Profile information",
		},
		"settingprofileimg.php": {
			details: "Profile settings",
			state: "Profile images",
		},
		"settingworkspace.php": {
			details: "Profile settings",
			state: "Workspace",
		},
		settinginfophp: { details: "Notification settings" },
		lives: { details: "Sketch- Browsing livestreams" },
		popular: { details: "Sketch- Viewing popular posts" },
		followings: { details: "Sketch- Viewing following posts" },
		tagshistory: { details: "Sketch- Viewing tags:", state: "Featured tags" },
		"upload.php": { details: "Submitting new novel" },
		discovery: { details: "Viewing recommended novels" },
		"ranking.php": { details: "Viewing novels ranking" },
```

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — APPROVED** [review]
