### PR TITLE
fix(Facebook): profile issue fixed

### LINKED ISSUE #6072: Facebook | facebook.com
### Description

When in privacy mode, is not showing the full details (Viewing Profile...)

### Steps to Reproduce

1. Go to facebook.com
2. Click on a random profile
3. Check the Discord Activity

### Screenshots

image

### Expected Behavior

Viewing Profile

### Actual Behavior

Facebook, only this, no more details

### Page URL

https://www.facebook.com/keedu.keedu.75

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.37.113 Chromium: 100.0.4896.88 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #6072
**Describe the changes in this pull request:**
Fixed profile not being displayed.
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

</details>

### CODE REVIEW

File: websites/F/Facebook/presence.ts [hunk 1]
```diff
@@ -406,24 +406,14 @@ presence.on("UpdateData", async () => {
...
-
-		if (!hasCommentInput) {
-			name = document
-				.querySelector(
-					"h2.gmql0nx0.l94mrbxd.p1ri9a11.lzcic4wl.d2edcug0.hpfvmrgz span.d2edcug0.hpfvmrgz.qv66sw1b.c1et5uql.lr9zc1uh.a8c37x1j.keod5gw0.nxhoafnm.aigsh9s9.fe6kdd0r.mau55g9w.c8b282yb.embtmqzv.hrzyx87i.m6dqt4wy.h7mekvxk.hnhda86s.oo9gr5id.hzawbc8m > span"
-				)
-				?.textContent.trim();
-		}
+		let name = document.querySelector("head > title").textContent;
+		name = name.replace(name.slice(-11), "");
```
Comment (Slowlife01) [inline websites/F/Facebook/presence.ts:416]:
```suggestion
		const name = document.title.slice(0,-11);
```

**Review by EncryptedDev — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]
