### PR TITLE
fix(Netflix): fix presence for alpha/beta extension

### LINKED ISSUE #7260: Netflix | netflix.com
### Steps to Reproduce

1. Visit netflix.com
2. Watch any show on [PreMiD-Beta](https://premid.app/beta) (or stable #7466)

### Expected Behavior

 Would expect it to show the show I'm watching on status.

### Actual Behavior

Presence does not show what Netflix show I'm watching.

### Page URL

1118280%2CNES_E5DCB5B6CE0824EBD068CE353C42D8-994911DC4F528C-A992686634_p_1680293608503%2CNES_E5DCB5B6CE0824EBD068CE353C42D8_p_1680293608503%2C%2C%2C%2C%2CVideo%3A80057134%2CdetailsPagePlayButton

### Screenshots

image
image

### Operating System

Windows 11

### Browser and Version

Brave Browser | V 1.49.132

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

- Fix netflix presence for Alpha/Beta extension. (Kinda unsure if this code's quality is high enough lol)
- Resolves #7260 
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/N/Netflix/presence.ts [hunk 1]
```diff
@@ -178,6 +179,21 @@ presence.on("UpdateData", async () => {
 		prevUrl = document.location.href;
 		browsingTimestamp = Math.floor(Date.now() / 1000);
 	}
+	if (
+		!scriptPushed &&
+		document.readyState !== "complete" &&
+		document.querySelector('[class="loading-children-container"]') &&
+		document.location.pathname.includes("/watch/")
+	) {
+		return;
```
Comment (Bas950) [inline websites/N/Netflix/presence.ts]: So if I am on a /watch/ url and I refresh the page, will the script even be loaded in?

File: websites/N/Netflix/presence.ts [hunk 2]
```diff
@@ -178,6 +179,21 @@ presence.on("UpdateData", async () => {
 		prevUrl = document.location.href;
 		browsingTimestamp = Math.floor(Date.now() / 1000);
 	}
+	if (
+		!scriptPushed &&
+		document.readyState !== "complete" &&
+		document.querySelector('[class="loading-children-container"]') &&
+		document.location.pathname.includes("/watch/")
+	)
+		return;
```
Comment (DarkVillager) [inline websites/N/Netflix/presence.ts:188]: It won't be loaded in if the page hasn't fully loaded or the netflix loading icon is present, otherwise it will

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]
