### PR TITLE
fix(Discord): dm username

### LINKED ISSUE #6474: discord premid it does not work
### Steps to Reproduce

https://discord.com

download premid discord web 

### Expected Behavior

that works normally like the other premid

### Actual Behavior

chat username not working

### Page URL

https://discord.com/

### Screenshots

eeeee
eee

### Operating System

Windows 10 home

### Browser and Version

brave, google

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Fixed once again showing the @username when dming someone
Resolves #6474

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

File: websites/D/Discord/presence.ts [hunk 1]
```diff
@@ -133,7 +133,10 @@ presence.on("UpdateData", async () => {
 								"input[name=channel_name]"
 							) as HTMLInputElement
 					  )?.value || "Undefined"
-					: `@${document.querySelector("h3")?.textContent || "Undefined"}`,
+					: `@${
+							document.querySelector("[aria-label='Channel header']")
+								?.firstElementChild?.children[2]?.textContent || "Undefined"
+					  }`,
```
Comment (N0chteil) [inline websites/D/Discord/presence.ts:142]:
```suggestion
					: document.querySelector("[aria-label='Channel header']")
							?.firstElementChild?.children[2]?.textContent || "Undefined",
```

Why the `@`?

File: websites/D/Discord/presence.ts [hunk 2]
```diff
@@ -133,7 +133,13 @@ presence.on("UpdateData", async () => {
...
 							) as HTMLInputElement
 					  )?.value || "Undefined"
-					: `@${document.querySelector("h3")?.textContent || "Undefined"}`,
+					: `@${
+							document.querySelector("[aria-label='Channel header']")
+								?.firstElementChild?.children[2]?.textContent ||
+							document.querySelector("head > title")?.textContent === "Discord"
+								? "undefined"
+								: document.querySelector("head > title")?.textContent
+					  }`,
```
Comment (N0chteil) [inline websites/D/Discord/presence.ts:142]:
```suggestion
					: document.querySelector("[aria-label='Channel header']")
							?.firstElementChild?.children[2]?.textContent ||
					  "Undefined"?.firstElementChild?.children[2]?.textContent ||
					  document.querySelector("head > title")?.textContent === "Discord"
					? "undefined"
					: document.querySelector("head > title")?.textContent,
```

Why the `@`?

**Review by EncryptedDev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Comment by EncryptedDev** [comment]
Thank you for improving the store! 🚀
