### PR TITLE
🐛Fixed various bugs within hanime Presence [NSFW]

### LINKED ISSUE #2335: hanime bug report NSFW in screenshot
**Describe the Bug**

The status for hanime only shows browsing even if you're watching a video it never shows the name or the time you're at in the video
**Steps to Reproduce**

1. Get https://premid.app/store/presences/hanime
2. Go to https://hanime.tv
3.Once on hanime select a video and view status

**Expected Behavior**

Expected behavior is that the Name appears and probably the time you're at in the video
**Screenshots**

unknown

**Environment**

- OS: Windows 10 2004
- Browser: Google Chrome
- Version: Version 86.0.4240.75 (Official Build) (64-bit)

**Additional context**
     Oh another thing would it be possible to show the nhentai number instead of the name because most nhentai names exceed 200 characters

### LINKED ISSUE #2535: Hanime Presence Bug
**Describe the Bug**

Bug is that  it only shows browsing. if you  go to a video and start watching it it doesnt show  the name  and stuff it just shows "Browsing.."
**Steps to Reproduce**

1.  Go to video - status doesn't update.

**Expected Behavior**

the  rich presence to be updated. containing the video name and   how much time left for the episode to   finish
**Screenshots**
**Environment**

- OS: Windows 10
- Browser: OperaGX
- Version: Latest

### PR DESCRIPTION
**Pull request by StrikerFRFX**
**Preword**

As much as I've tested and tried, the timestamps functionality seems to be completely broken with this site.
I looked into the JS console as I began playing a video and it seems that the video class is completely null despite actually playing a video. I've hopefully fixed the timestamps functionality so that if the site were to start working again and actually return the video class when it plays, the presence timestamps should show. But of course, I have no way to fully test (but the code is there). If anyone thinks I missed anything with this functionality, please let me know. I would appreciate any suggestions but as Ririxi has said (in the presence-dev discord channel), this could simply be a site issue and not actually a presence issue.

That aside, here are the two screenshots of the now functional presence (its 2 possible states).

Any issues with this PR at all please LMK.

**Screenshots**
x2da1VCRm9
GfDAmUGiun

The above screenshots are what shows on the Homepage and when watching a video respectively.

Resolves #2535, resolves #2335

### CODE REVIEW

**Review by Bas950 — APPROVED** [review]

File: websites/H/hanime/presence.ts [hunk 1]
```diff
@@ -1,85 +1,71 @@
...
+      presenceData.startTimestamp = timestamps[0];
+      presenceData.endTimestamp = timestamps[1];
+  
+      presence.setTrayTitle(
+        paused
+          ? ""
+          : videoTitle !== null
+          ? videoTitle.textContent
+          : "Title not found"
+      );
```
Comment (ririxidev) [inline websites/H/hanime/presence.ts:50]: you shouldn't set anything if you don't have anything to set for macOS tray.

**Review by ririxidev — CHANGES_REQUESTED** [review]

File: websites/H/hanime/presence.ts (hunk 1 above)
Comment (StrikerFRFX) [reply websites/H/hanime/presence.ts:50]: yeah OK, was debating removing this but left it in. Will remove since it's from the older versions anyway

**Review by Bas950 — APPROVED** [review]

**Review by ririxidev — APPROVED** [review]
